appname = Rental-Property-REST-API
httpport = 8080
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
sqlconn =


# Rental Property Data Path
property_data_path = data/rental_properties.json